internsidor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.http import HttpResponse
from django.views.generic.base import TemplateView

from ajax_select import urls as ajax_select_urls

import batadasen


def auth_check(request):
    """
    Empty response view for use with Nginx auth_request
    """
    if request.user.is_authenticated:
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=401, headers={"WWW-Authenticate": "Bearer"})


if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns = [
        # This is a hack to workaround the fact that the admin logout link uses GET but
        # the mozilla_django_oidc logout page requires a POST request.
        # The logout_get.html simply instructs the user to logout with the regular logout button.
        path(
            "admin/logout/",
            TemplateView.as_view(template_name="batadasen/logout_get.html"),
        ),
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("auth_check", auth_check, name="auth-check"),
        path("", batadasen.views.index_view),
    ]
else:
    urlpatterns = [
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        # A simple login view for dev setups that don't have keycloak available
        path(
            "login/",
            auth_views.LoginView.as_view(template_name="batadasen/dev_login.html"),
            name="login",
        ),
        # Fake the oidc_logout url to make the logout button happy
        path("logout/", auth_views.LogoutView.as_view(), name="oidc_logout"),
        path("", batadasen.views.index_view),
    ]

    # Used to serve uploaded files during development, NOT FOR PRODUCTION USE
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spexflix/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"productions", views.ProductionViewSet)

app_name = "spexflix"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.ProductionList.as_view(), name="index"),
    path(
        "productions/<int:pk>",
        views.ProductionDetail.as_view(),
        name="production-detail",
    ),
    path("video/<int:pk>", views.VideoDetail.as_view(), name="video-detail"),
]

spexflix/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
import os

UPLOAD_PREFIX = "spexflix"


def get_video_upload_path(instance, filename):
    if instance.production is None:
        path = os.path.join(UPLOAD_PREFIX, "misc", filename)
    else:
        path = os.path.join(UPLOAD_PREFIX, instance.production.short_name, filename)

    return instance.video_file.storage.get_available_name(path)


def get_subtitle_upload_path(instance, filename):
    if instance.video.production is None:
        path = os.path.join(UPLOAD_PREFIX, "misc", filename)
    else:
        path = os.path.join(
            UPLOAD_PREFIX, instance.video.production.short_name, "subtitles", filename
        )

    return instance.subtitle_file.storage.get_available_name(path)


def get_poster_upload_path(instance, filename):
    return instance.poster_image.storage.get_available_name(
        os.path.join(UPLOAD_PREFIX, instance.short_name, filename)
    )


class VideoType(models.TextChoices):
    SHOW = "SHOW", "Föreställning"
    EXTRA = "EXTRA", "Extramaterial"
    OTHER = "OTHER", "Övrigt"


class Production(models.Model):
    short_name = models.CharField(
        max_length=10,
        verbose_name="Kortnamn",
        help_text="T.ex Spex-19, men kan också vara något annat som identifierar en speciell uppsättning (t.ex SM-17 eller Jubel-35)",
    )
    year = models.PositiveSmallIntegerField(verbose_name="År")
    title = models.CharField(max_length=200, verbose_name="Titel")
    subtitle = models.CharField(max_length=200, verbose_name="Undertitel", blank=True)
    poster_image = models.ImageField(
        null=True,
        blank=True,
        verbose_name="Omslagsbild",
        upload_to=get_poster_upload_path,
    )
    information = models.TextField(
        max_length=2000,
        blank=True,
        verbose_name="Information",
        help_text="Beskriv spexets handling eller annat som kan vara intressant.",
    )

    class Meta:
        verbose_name = "Uppsättning"
        verbose_name_plural = "Uppsättningar"
        ordering = ["-year"]

    def __str__(self):
        return "{} - {}".format(self.short_name, self.title)

    @property
    def main_show(self):
        return self.videos.filter(video_type=VideoType.SHOW).first()


class Video(models.Model):
    title = models.CharField(
        verbose_name="Videotitel",
        max_length=200,
        help_text='Vad är detta för video? Typiskt "Föreställning" eller "Spexialmaterial" eller liknande',
    )
    video_file = models.FileField(
        verbose_name="Fil",
        upload_to=get_video_upload_path,
        validators=[FileExtensionValidator(["mp4", "m4v"])],
    )
    information = models.TextField(
        verbose_name="Information",
        max_length=500,
        blank=True,
        help_text="Ytterligare information om videon, t.ex inspelningsdatum, plats eller vem som har gjort klipping etc",
    )
    production = models.ForeignKey(
        Production,
        models.SET_NULL,
        verbose_name="Uppsättning",
        null=True,
        blank=True,
        related_name="videos",
    )

    video_type = models.CharField(
        max_length=10,
        verbose_name="Videotyp",
        choices=VideoType.choices,
        default=VideoType.SHOW,
    )

    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Videos"

    def __str__(self):
        if self.production is None:
            return "{} ({})".format(self.title, self.video_file.name)
        else:
            return "{} - {}".format(self.production.short_name, self.title)


class SubtitleTrack(models.Model):
    name = models.CharField(verbose_name="Namn", max_length=20)
    subtitle_file = models.FileField(
        verbose_name="Fil",
        upload_to=get_subtitle_upload_path,
        validators=[FileExtensionValidator(["vtt"])],
    )
    video = models.ForeignKey(
        Video, models.CASCADE, verbose_name="Video", related_name="subtitles"
    )

    class Meta:
        verbose_name = "Undertextspår"
        verbose_name_plural = "Undertextspår"

    def __str__(self):
        return "{} - {}".format(self.video, self.name)

spexflix/views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from rest_framework import viewsets, permissions
from . import models, serializers


@method_decorator(login_required, name="dispatch")
class ProductionList(ListView):
    model = models.Production
    context_object_name = "production_list"
    template_name = "spexflix/production_list.html"


@method_decorator(login_required, name="dispatch")
class ProductionDetail(DetailView):
    model = models.Production
    context_object_name = "production"
    template_name = "spexflix/production_detail.html"


@method_decorator(login_required, name="dispatch")
class VideoDetail(DetailView):
    model = models.Video
    context_object_name = "video"
    template_name = "spexflix/video_detail.html"


class ProductionViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = models.Production.objects.all()
    permission_classes = (permissions.IsAuthenticated,)
    serializer_class = serializers.ProductionSerializer

spexflix/templates/spexflix/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    {% block head %} {% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'spexflix/style.css' %}" />
    <script src="{% static 'spexflix/script.js' %}"></script>

    <title>{% block title %} {% endblock %}</title>
</head>

<body style="background-image: url({% static 'spexflix/background.png' %});">
    <!--Navigation bar-->
    <div id="navbar" class="bg-dark">
        <a href="{% url 'spexflix:index' %}"><img class="navbar-element" src="../../static/spexflix/spexflix-logo.png"
                alt="spexflix" style="width: 130px;" /></a>
        <a href="{% url 'admin:index' %}"><span class="glyphicon glyphicon-lock navbar-element"
                style="float: right; color:gray"></span></a>
        <br style="clear: both;">
    </div>

    <!--Content-->
    {% load i18n %}
    <div style="width: 90%; margin: auto;">
        {% block content %} {% endblock %}
    </div>
</body>

</html>

spexflix/templates/spexflix/production_detail.html
{% extends 'spexflix/base.html' %}
{% load i18n %}

{% block title %}Spexflix - {{ production }}{% endblock %}

{% block content %}

<h1>{{ production }}</h1>
<a href="{% url 'spexflix:index' %}">Tillbaka till uppsättningar</a>

<h2>Videos:</h2>

<ul>
    {% for video in production.videos.all %}
    <li>
        <a href="{% url 'spexflix:video-detail' video.pk %}">{{ video.title }}</a>
    </li>
    {% endfor %}
</ul>

{% endblock %}

spexflix/templates/spexflix/production_list.html
{% extends 'spexflix/base.html' %}
{% load i18n %}
{% block head %}
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
{% endblock %}

{% block title %}Spexflix{% endblock %}

{% block content %}
<h2>Uppsättningar</h2>
<div class="row" style="margin-top: 7vh;">
  <div class="MultiCarousel" data-items="1,2,3,4" data-slide="1" id="MultiCarousel" data-interval="1000">
    <div class="MultiCarousel-inner">
      {% for production in production_list %}{%if production.videos.first%}
      <div class="item">
        <div class="pad15">
          {%if production.main_show%}
          {%if production.poster_image%}
          <a class="poster" href="{% url 'spexflix:video-detail' production.main_show.pk %}"
            style="background-image: url({{ production.poster_image.url }});">
          </a>
          {%else%}
          <a class="poster" href="{% url 'spexflix:video-detail' production.main_show.pk %}"
            style="background-color: black;">
          </a>
          {%endif%}
          {%else%}
          {%if production.poster_image%}
          <a class="poster" href="{% url 'spexflix:video-detail' production.videos.first.pk %}"
            style="background-image: url({{ production.poster_image.url }});">
          </a>
          {%else%}
          <a class="poster" href="{% url 'spexflix:video-detail' production.videos.first.pk %}"
            style="background-color: black;">
          </a>
          {%endif%}
          {%endif%}
          <h2 class="poster-text">{{ production.short_name}}</h2>
        </div>
      </div>
      {%endif%}{% endfor %}
    </div>
    <button class="leftLst"><span class="glyphicon glyphicon-menu-left"></span></button>
    <button class="rightLst"><span class="glyphicon glyphicon-menu-right"></span></button>
  </div>
</div>

{% endblock %}

spexflix/templates/spexflix/video_detail.html
{% extends 'spexflix/base.html' %}
{% load i18n %}
{% block head %}
<link href="https://vjs.zencdn.net/7.7.5/video-js.css" rel="stylesheet" />
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
{% endblock %}

{% block title %}Spexflix - {{ production }}{% endblock %}

{% block content %}
<div id="video-container">
    <a href="{% url 'spexflix:index' %}" class="glyphicon glyphicon-remove back-arrow"></a>
    <!--Video-->
    <div class="w3-twothird" style="padding: 20px 20px 5px 20px;">
        <video id="my-video" class="video-js" controls preload="auto" data-setup="{}">
            <source src="{{ video.video_file.url }}" type="video/mp4" />

            {% for subtitle in video.subtitles.all %}
            <track kind="captions" src="{{ subtitle.subtitle_file.url }}" srclang="sv" label="{{ subtitle.name }}"
                default>
            {% endfor %}

            <p class="vjs-no-js">
                To view this video please enable JavaScript, and consider upgrading to a
                web browser that
                <a href="https://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
            </p>
        </video>
        <h5>{{ video.title }}</h5>
        <h6 style="width: 90%;">
            {{ video.information|linebreaks }}
        </h6>
    </div>
    <!--Information-->
    <div class="w3-third" style="padding: 0 20px 0 20px; ">
        <h1 class="production-title">{{ video.production.title }}</h1>
        {%if video.production.subtitle %}
        <h3 class="production-title">eller {{ video.production.subtitle }}</h3>
        {%endif%}
        {%if video.production.information %}
        <h6 id="production-information">{{ video.production.information|linebreaks }}</h6>
        {%endif%}
        <hr>
        <div style="background-color: rgba(0, 0, 0, 0.5);">
            {% for vid in video.production.videos.all %}
            {% if vid.video_type == 'SHOW' %}
            {%if vid == video%}
            <a href="{% url 'spexflix:video-detail' vid.pk %}" class="video-tooltip is-showing">
                <h5>{{ vid.title }}</h5>
                <h6 class="video-info-text">{{ vid.information }}</h6>
            </a>
            {%else%}
            <a href="{% url 'spexflix:video-detail' vid.pk %}" class="video-tooltip">
                <h5>{{ vid.title }}</h5>
                <h6 class="video-info-text">{{ vid.information }}</h6>
            </a>
            {%endif%}
            {% endif %}
            {% endfor %}

            {% for vid in video.production.videos.all %}
            {% if vid.video_type != 'SHOW' %}
            {%if vid == video%}
            <a href="{% url 'spexflix:video-detail' vid.pk %}" class=" video-tooltip is-showing">
                <h5>{{ vid.title }}</h5>
                <h6 class="video-info-text">{{ vid.information }}</h6>
            </a>
            {%else%}
            <a href="{% url 'spexflix:video-detail' vid.pk %}" class="video-tooltip">
                <h5>{{ vid.title }}</h5>
                <h6 class="video-info-text">{{ vid.information }}</h6>
            </a>
            {%endif%}
            {% endif %}
            {% endfor %}
        </div>
    </div>
    <br style="clear: both;">
</div>






{% endblock %}