assetmanager/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from assetmanager.views import (
    AssetListView,
    AssetDetailView,
    AssetModelDetailView,
    new_logentry_view,
    new_asset_view,
    new_assetmodel_view,
    new_category_view,
    search_view,
)


app_name = "assetmanager"
urlpatterns = [
    path("assets/", AssetListView.as_view(), name="asset_list"),
    path("assets/add/", new_asset_view, name="asset_add"),
    path("assets/search/", search_view, name="asset_search"),
    path("assets/<int:number>/", AssetDetailView.as_view(), name="asset_detail"),
    path(
        "assets/<int:number>/new-log-entry/", new_logentry_view, name="create_log_entry"
    ),
    path(
        "assetmodels/<int:pk>/",
        AssetModelDetailView.as_view(),
        name="assetmodel_detail",
    ),
    path("assetmodels/add/", new_assetmodel_view, name="assetmodel_add"),
    path("categories/add/", new_category_view, name="category_add"),
    path("", RedirectView.as_view(pattern_name="asset_list", permanent=False)),
]

batadasen/urls.py
from django.urls import path

from . import views

app_name = "batadasen"
urlpatterns = [
    path("activate", views.activation_view, name="activate"),
    path("email_lists/", views.email_list_filter, name="emaillist_list"),
    path(
        "email_lists/<str:alias>/",
        views.EmailListDetailView.as_view(),
        name="emaillist_detail",
    ),
    path("settings/", views.PersonSelfView.as_view(), name="person_settings"),
    path(
        "settings/extra_email/",
        views.ExtraEmailView.as_view(),
        name="person_extra_email",
    ),
    path("persons/", views.PersonListView.as_view(), name="person_list"),
    path("persons/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    path("hundraklubben/", views.Club100.as_view(), name="hundraklubben"),
    path("medals/", views.Medals.as_view(), name="medals"),
    path("productions/", views.ProductionListView.as_view(), name="production_list"),
    path(
        "productions/<int:pk>/",
        views.ProductionDetailView.as_view(),
        name="production_detail",
    ),
    path(
        "productions/<int:pk>/<str:group_shortname>/",
        views.ProductionGroupDetailView.as_view(),
        name="production_group_detail",
    ),
    path(
        "association/",
        views.AssociationYearListView.as_view(),
        name="associationyear_list",
    ),
    path(
        "association/<int:pk>/",
        views.AssociationYearDetailView.as_view(),
        name="associationyear_detail",
    ),
    path(
        "association/<int:pk>/<str:group_shortname>/",
        views.AssociationYearGroupDetailView.as_view(),
        name="associationyear_group_detail",
    ),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
    path("api/users", views.UserList.as_view()),
    path("api/users_count", views.user_count),
    path("no_admin/", views.no_admin_view, name="no_admin"),
    path("", views.index_view, name="index"),
]

internsidor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.http import HttpResponse
from django.views.generic.base import TemplateView

from ajax_select import urls as ajax_select_urls

import batadasen


def auth_check(request):
    """
    Empty response view for use with Nginx auth_request
    """
    if request.user.is_authenticated:
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=401, headers={"WWW-Authenticate": "Bearer"})


if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns = [
        # This is a hack to workaround the fact that the admin logout link uses GET but
        # the mozilla_django_oidc logout page requires a POST request.
        # The logout_get.html simply instructs the user to logout with the regular logout button.
        path(
            "admin/logout/",
            TemplateView.as_view(template_name="batadasen/logout_get.html"),
        ),
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("auth_check", auth_check, name="auth-check"),
        path("", batadasen.views.index_view),
    ]
else:
    urlpatterns = [
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        # A simple login view for dev setups that don't have keycloak available
        path(
            "login/",
            auth_views.LoginView.as_view(template_name="batadasen/dev_login.html"),
            name="login",
        ),
        # Fake the oidc_logout url to make the logout button happy
        path("logout/", auth_views.LogoutView.as_view(), name="oidc_logout"),
        path("", batadasen.views.index_view),
    ]

    # Used to serve uploaded files during development, NOT FOR PRODUCTION USE
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcounter/urls.py
from django.urls import path

from showcounter import views

app_name = "showcounter"
urlpatterns = [
    path("production/<int:number>", views.production, name="production"),
    path("", views.overview, name="overview"),
]

spexflix/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"productions", views.ProductionViewSet)

app_name = "spexflix"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.ProductionList.as_view(), name="index"),
    path(
        "productions/<int:pk>",
        views.ProductionDetail.as_view(),
        name="production-detail",
    ),
    path("video/<int:pk>", views.VideoDetail.as_view(), name="video-detail"),
]

batadasen/views.py
from datetime import datetime
from django.conf import settings
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import connection
from django.db.models import Q, Count, Min, F
from django.db.models.functions import Collate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    CreateView,
    TemplateView,
)
from django_filters.filterset import FilterSet
import django_tables2 as tables

from rest_framework import generics, filters
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework_api_key.permissions import HasAPIKey
import django_filters

from . import forms, models, serializers
from showcounter.models import Performance

if settings.PROVISION_GSUITE_ACCOUNTS:
    from . import gsuite

User = get_user_model()


def swedish_order(field: str):
    """Use collation to get Swedish ordering for a field.

    This collation is not available in SQLite so it is skipped during local development."""
    if connection.vendor == "postgresql":
        return Collate(F(field), "sv-SE-x-icu")
    return field


def activation_view(request):
    token = request.GET.get("token")
    activations = models.UserActivation.objects.filter(token=token)

    bad_token = False
    if token is None or not activations.exists():
        bad_token = True
    else:
        if timezone.now() > activations.first().valid_until:
            bad_token = True

    if bad_token:
        return HttpResponse(
            "Du har nog följt en gammal länk eller så har den kopierats fel"
        )

    activation = activations.first()
    person = activation.person

    if request.method == "POST":
        form = forms.ActivationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]

            user = User(username=username)
            user.save()

            if person.user is not None:
                person.user.delete()

            person.user = user
            person.save()

            if (
                settings.PROVISION_GSUITE_ACCOUNTS
                and activation.provision_gsuite_account
            ):
                gsuite.create_user(
                    person.user.username, person.first_name, person.last_name
                )

            activations.delete()

            return redirect("batadasen:person_settings")

    else:
        form = forms.ActivationForm()

    return render(request, "batadasen/activate.html", {"form": form, "person": person})


@method_decorator(login_required, name="dispatch")
class EmailListListView(ListView):
    model = models.EmailList

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["email_domain"] = settings.EMAIL_DOMAIN
        return context


@method_decorator(login_required, name="dispatch")
class EmailListDetailView(DetailView):
    model = models.EmailList
    fields = ["recipients"]
    slug_field = "alias"
    slug_url_kwarg = "alias"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["email_domain"] = settings.EMAIL_DOMAIN
        if context["object"].alias.endswith("gruppledare"):
            context["gruppledare"] = True
        return context


class PersonTable(tables.Table):
    member_number = tables.URLColumn(verbose_name="Medlem")
    spex_name = tables.Column(default="")

    class Meta:
        model = models.Person
        template_name = "django_tables2/bootstrap4-responsive.html"
        fields = ("member_number", "first_name", "last_name", "spex_name")
        row_attrs = {
            "class": lambda record: "text-muted font-italic" if record.deceased else ""
        }


@method_decorator(login_required, name="dispatch")
class PersonListView(tables.SingleTableView):
    table_class = PersonTable
    queryset = models.Person.objects.filter(member_number__lt=5000).all()
    template_name = "person_list.html"
    table_pagination = False


@method_decorator(login_required, name="dispatch")
class PersonDetailView(DetailView):
    model = models.Person


@method_decorator(login_required, name="dispatch")
class PersonSelfView(UpdateView):
    form_class = forms.PersonForm
    template_name = "batadasen/person_settings.html"
    success_url = reverse_lazy("batadasen:person_settings")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "object" in context:
            context["extra_emails"] = models.ExtraEmail.objects.filter(
                person=context["object"]
            )
        return context

    def get_object(self, queryset=None):
        return models.Person.objects.filter(user=self.request.user).first()


@method_decorator(login_required, name="dispatch")
class ExtraEmailView(CreateView):
    form_class = forms.ExtraEmailForm
    template_name = "batadasen/extraemail_form.html"
    success_url = reverse_lazy("batadasen:person_settings")

    def form_valid(self, form):
        if form.is_valid():
            extra_email = form.save(commit=False)
            extra_email.person = self.request.user.person
            extra_email.save()
        return redirect("batadasen:person_settings")


@method_decorator(login_required, name="dispatch")
class ProductionListView(ListView):
    model = models.Production


@method_decorator(login_required, name="dispatch")
class ProductionDetailView(DetailView):
    model = models.Production

    # This dance is done to order the memberships in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = []
        for group in context["object"].groups.all():
            memberships = group.memberships.annotate(
                first_production_id=Min(
                    "person__production_memberships__group__production__pk"
                )
            ).order_by(
                F("title").asc(nulls_last=True),
                swedish_order("person__first_name"),
                swedish_order("person__last_name"),
            )

            if not memberships.exists():
                continue
            result_group = dict()
            result_group["group"] = group
            result_group["memberships"] = memberships
            groups.append(result_group)
        context["groups"] = groups

        previous_production = (
            self.model.objects.filter(number__lt=context["object"].number)
            .order_by("-number")
            .only("number")
            .first()
        )
        context["previous"] = (
            previous_production.number if previous_production else None
        )

        next_production = (
            self.model.objects.filter(number__gt=context["object"].number)
            .only()
            .order_by("number")
            .only("number")
            .first()
        )
        context["next"] = next_production.number if next_production else None

        return context


@method_decorator(login_required, name="dispatch")
class ProductionGroupDetailView(DetailView):
    model = models.Production
    template_name = "batadasen/production_group_detail.html"  # skapa ev ny template

    # This dance is done to order the memberships in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        previous_production = (
            self.model.objects.filter(number__lt=context["object"].number)
            .order_by("-number")
            .only("number")
            .first()
        )
        context["previous"] = (
            previous_production.number if previous_production else None
        )

        next_production = (
            self.model.objects.filter(number__gt=context["object"].number)
            .only()
            .order_by("number")
            .only("number")
            .first()
        )
        context["next"] = next_production.number if next_production else None

        group_shortname = self.kwargs["group_shortname"]
        context["group_shortname"] = group_shortname

        group = context["object"].groups.filter(group_type_id=group_shortname).first()
        if not group:
            return context

        memberships = group.memberships.annotate(
            first_production_id=Min(
                "person__production_memberships__group__production__pk"
            )
        ).order_by(
            F("title").asc(nulls_last=True),
            swedish_order("person__first_name"),
            swedish_order("person__last_name"),
        )

        context["group"] = group
        context["memberships"] = memberships

        return context


@method_decorator(login_required, name="dispatch")
class AssociationYearListView(ListView):
    model = models.AssociationYear


@method_decorator(login_required, name="dispatch")
class AssociationYearDetailView(DetailView):
    model = models.AssociationYear

    # This dance is done to order the activities in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = []
        for group in context["object"].groups.all():
            activities = group.activities.order_by(
                F("title").asc(nulls_last=True),
                swedish_order("person__first_name"),
                swedish_order("person__last_name"),
            )

            if not activities.exists():
                continue
            result_group = {
                "group": group,
                "activities": activities,

batadasen/templates/batadasen/associationyear_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Verksamhetsåret {{ object }}{% endblock %}

{% block content %}
<div class="col-xl-8">
    <div class="container-fluid">
        <div class="row h2">
            <div class="col-2 text-left">{% if previous %}<a class="btn btn-outline-secondary bi bi-caret-left-fill" href="{% url 'batadasen:associationyear_detail' previous %}" class="silent-link"></a>{% endif %}</div>
            <div class="col-8 text-center">Verksamhetsåret {{ object }}</div>
            <div class="col-2 text-right">{% if next %}<a class="btn  btn-outline-secondary bi bi-caret-right-fill" href="{% url 'batadasen:associationyear_detail' next %}" class="silent-link"></a>{% endif %}</div>
        </div>
    </div>
    <table class="table table-sm table-striped">
        {% for group in groups %}
        <tr class="table-primary">
            <th colspan="4">
                <a href="{% url 'batadasen:associationyear_group_detail' object.end_year group.group.group_type.short_name %}">{{ group.group.group_type.name }} ({{ group.group.group_type.short_name }})</a>
            </th>
        </tr>
        {% for activity in group.activities %}
        <tr>
            <td><a href="{% url 'batadasen:person_detail' activity.person.member_number %}">{{ activity.person.member_number }}</a></td>
            <td>{{ activity.person.first_name }} {% if activity.person.spex_name %}"{{ activity.person.spex_name }}" {% endif %}{{ activity.person.last_name }}</td>
            <td>{% if activity.title %}{{ activity.title }}{% endif %}</td>
            <td>{% if activity.to_date %}T.o.m. {{ activity.to_date }}{% endif %}</td>
        </tr>
        {% endfor %}    
        {% endfor %}
    </table>
</div>
{% endblock %}

batadasen/templates/batadasen/associationyear_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Verksamhetsår{% endblock %}

{% block content %}
<h2>Verksamhetsår</h2>
<table class="table table-sm">
    <tr>
        <th>År</th>
    </tr>
    {% for year in object_list %}
    <tr>
        <td><a href="{% url 'batadasen:associationyear_detail' year.end_year %}"></ahref>{{ year }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

batadasen/templates/batadasen/event_add.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}

{% block title %}Arrangera ett evenemang{% endblock %}

{% block content %}

<h2>Arrangera nått kul!</h2>

{{ form.errors }}
{{ form.non_field_errors }}
<form method="post" class="">
	{% csrf_token %}
	{% crispy form %}
</form>

{% endblock %}

batadasen/templates/batadasen/index.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}LiSS internsidor{% endblock %}

{% block content %}
<h1>LiSS internsidor</h1>
<p>Här finns diverse funktioner som kan vara användbara för spexare:</p>
<ul>
    <li><a href="{% url 'batadasen:production_list' %}">Lista uppsättningar och medlemmar</a></li>
    <li><a href="{% url 'batadasen:emaillist_list' %}">Se vilka e-postlistor som finns</a></li>
    <li><a href="{% url 'batadasen:person_settings' %}">Redigera dina uppgifter och inställningar</a></li>
    <li><a href="{% url 'assetmanager:asset_list' %}">Se och uppdatera info om spexets inventarier</a></li>
    <li><a href="{% url 'showcounter:overview' %}">Räkna hur många föreställningar du varit med på!</a></li>
    <li><a href="{% url 'spexflix:index' %}">Spexflix - Kolla på gamla spex!</a></li>
    <li><a href="https://old.studentspex.se">Gamla sidor som inte flyttats ännu</a></li>
</ul>
{% endblock %}

batadasen/templates/batadasen/person_detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block title %}Persondetaljer{% endblock %}

{% block content %}
<h1>Detaljer för medlem {{ object.member_number }}</h1>

{% if not object.currently_member %}
<div class="alert alert-warning" role="alert">
Personen har inte betalat medlemsavgift och är för närvarande inte medlem i föreningen!
</div>
{% endif %}

{% if request.user.person == object %}

<div class="alert alert-primary" role="alert">
    Det här är du! Gå till <a href="{% url 'batadasen:person_settings' %}">inställningar</a> för att redigera din info.
</div>

{% elif object.privacy_setting == 'PVT' %}

<div class="alert alert-danger" role="alert">
    Personen har valt att dölja sina kontaktuppgifter för andra medlemmar.

    {% if perms.batadasen.view_private_info %}
    <br>Du kan bara se dess uppgifter för att du är administratör.
    {% endif %}
</div>

{% endif %}

<table class="table table-sm table-striped">
<tr>
    <td>Medlemsnummer</td>
    <td>{{ object.member_number }}</a></td>
</tr>
<tr>
    <td>Namn</td>
    <td>{{ object.first_name }} {% if object.spex_name %}"{{ object.spex_name }}" {% endif %}{{ object.last_name }}</td>
</tr>
{% if object.privacy_setting == 'OPN' or perms.batadasen.view_private_info %}
<tr>
    <td>E-post</td>
    <td>{% if object.address_list_email %}{{ object.address_list_email }}{% else %}{{ object.email }}{% endif %}</a></td>
</tr>
<tr>
    <td>Telefonnr (mobil)</td>
    <td>{{ object.phone_mobile }}</a></td>
</tr>
<tr>
    <td>Telefonnr (hem)</td>
    <td>{{ object.phone_home }}</a></td>
</tr>
<tr>
    <td>Telefonnr (arbete)</td>
    <td>{{ object.phone_work }}</a></td>
</tr>
<tr>
    <td>Gatuadress</td>
    <td>{{ object.street_address }}</a></td>
</tr>
<tr>
    <td>Postadress</td>
    <td>{{ object.postal_code }} {{ object.postal_locality }}</a></td>
</tr>
{% endif %}
</table>

<div class="achievements">
    {% if object.medal_2 %}<div class="achievement-2 shimmer"></div>{% endif %}
    {% if object.medal_4 %}<div class="achievement-4 shimmer"></div>{% endif %}
    {% if object.medal_6 %}<div class="achievement-6 shimmer"></div>{% endif %}
    {% if object.hundred_club %}<div class="achievement-100 tick"></div>{% endif %}
</div>

<h2>Uppsättningshistorik</h2>
<table class="table table-sm table-striped">
<tr>
    <th>År</th>
    <th>Uppsättning</th>
    <th>Grupp</th>
    <th>Titel</th>
    <th>Kommentar</th>
</tr>
{% for membership in object.production_memberships.all %}
<tr>
    <td>{{ membership.group.production.year }}</td>
    <td><a href="{% url 'batadasen:production_detail' membership.group.production.number %}">{{ membership.group.production.main_title }}</a></td>
    <td>{{ membership.group.group_type.short_name }}</td>
    <td>{% if membership.title %}{{ membership.title }}{% endif %}</td>
    <td>{{ membership.comment }}</td>
</tr>
{% endfor %}
</table>

<h2>Föreningsuppdrag</h2>
<table class="table table-sm table-striped">
<tr>
    <th>Verksamhetsår</th>
    <th>Grupp</th>
    <th>Titel</th>
</tr>
{% for activity in object.association_activities.all %}
<tr>
    <td><a href="{% url 'batadasen:associationyear_detail' activity.group.year.end_year %}">{{ activity.group.year }}</a></td>
    <td>{{ activity.group.group_type.name }}</td>
    <td>{% if activity.title %}{{ activity.title }}{% endif %}</td>
</tr>
{% endfor %}
</table>

<h2>Medlemskapshistorik</h2>
<p>Här beskrivs personens medlemskap i föreningen genom åren.</p>
<table class="table table-sm table-striped">
    <tr>
        <th>Verksamhetsår</th>
        <th>Typ</th>
    </tr>
    {% for membership in object.association_memberships.all %}
    <tr>
        {% if membership.membership_type == 'STD' %}
        <td>{{ membership.year }}</td>
        {% else %}
        <td>Från och med {{ membership.year }}</td>
        {% endif %}
        <td>{{ membership.get_membership_type_display }}</td>
    </tr>
    {% endfor %}
</table>

<h2>Sammanfattning</h2>
<table class="table table-sm table-striped">
    <tr>
        <th>Kategori</th>
        <th>Antal</th>
        <th>Förklaring</th>
    </tr>
    <tr>
        <td>Spexår</td>
        <td>{{ object.active_years | length }}</td>
        <td>Antal verksamhetsår med medlemsskap i minst en uppsättningsgrupp eller föreningsgrupp.</td>
    </tr>
    <tr>
        <td>Uppsättningar</td>
        <td>{{ object.productions | length }}</td>
        <td>Antalet uppsättningar med medlemsskap i minst en uppsättningsgrupp.</td>
    </tr>
    <tr>
        <td>Föreställningar</td>
        <td>{{ object.performances.all | length }}</td>
        <td>Självrapporterat antal föreställningar.</td>
    </tr>
</table>
{% endblock %}

batadasen/templates/batadasen/person_settings.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Inställningar{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

{% if object %}

<div class="col-xl-6">

<h2>Inställningar och personuppgifter</h2>

<p>
    Här redigerar du dina personuppgifter och inställningar för hemsidan. 
</p>

<p>
<a href="{% url 'batadasen:person_detail' object.member_number %}">Gå till din profilsida</a>
</p>

{% if object.currently_member %}
<div class="alert alert-success" role="alert">
    Du är medlem i föreningen
</div>
{% else %}
<div class="alert alert-warning" role="alert">
    Du är inte medlem i föreningen
</div>
{% endif %}

<h4>
Medlem {{ object.member_number }}, {{ object.first_name }}{% if object.spex_name %} "{{ object.spex_name }}"{% endif %} {{ object.last_name }}
</h4>
<p>
Användarnamn: {{ object.user.username }}
</p>

<div>
{% crispy form form.helper %}
</div>

<div>
<h2>Extra mailadresser</h2>
<p>Vissa maillistor accepterar bara mail från spexare, baserat på vilken mailadress man skickar från. Om du behöver skicka mail från
    andra adresser än de du skrivit in ovan behöver du lägga till dem som extra mailadresser här (tidigare kallat vitlistan):
</p>
<ul>
{% for email in extra_emails %}
    <li>{{ email.email }}</li>
{% endfor %}
</ul>
<p><a href="{% url 'batadasen:person_extra_email' %}">Lägg till ny mailadress</a></p>
<p>Kontakta någon i styrelsen eller directionen om du vill ta bort en mailadress.</p>
</div>

</div>

{% else %}
<div class="alert alert-danger" role="alert">
Ditt användarkonto ({{ request.user }}) har ingen person kopplad till sig.
</div>

{% endif %}

{% endblock %}

batadasen/templates/batadasen/production_group_detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Uppsättningslista {{ group_shortname }}{% endblock %}

{% block content %}
<div class="col-xl-8">
    <div class="container-fluid">
        <div class="row h2">
            <div class="col-2 text-left">{% if previous %}<a class="btn btn-outline-secondary bi bi-caret-left-fill silent-link" href="{% url 'batadasen:production_group_detail' previous group_shortname %}"></a>{% endif %}</div>
            <div class="col-8 text-center">{% if group %}{{ group.group_type.name }}{% else %}{{ group_shortname}}{% endif %}: <a href="{% url 'batadasen:production_detail' object.number %}">{{ object.short_name }} - {{ object.main_title }}</a></div>
            <div class="col-2 text-right">{% if next %}<a class="btn  btn-outline-secondary bi bi-caret-right-fill silent-link" href="{% url 'batadasen:production_group_detail' next group_shortname %}"></a>{% endif %}</div>
        </div>
    </div>

    {% if group %}
    <p>Om bakgrunden är röd så är personen inte medlem i föreningen.</p>

    <table class="table table-sm table-striped">
    <tr class="table-primary"> <th colspan="4">{{ group.group_type.name }} ({{ group.group_type.short_name }})</th></tr>
        {% for membership in memberships %}
            {% if not membership.person.currently_member %}
    <tr class = "table-danger">
            {% else %}
    <tr>
            {% endif %}
        <td><a href="{% url 'batadasen:person_detail' membership.person.member_number %}">{{ membership.person.member_number }}</a></td>
        <td>
            {{ membership.person.first_name }} {% if membership.person.spex_name %}"{{ membership.person.spex_name }}" {% endif %}{{ membership.person.last_name }}{% if membership.first_production_id == object.pk %}*{% endif %}
        </td>
        <td>{% if membership.title %}{{ membership.title }}{% endif %}</td>
        <td>{% if membership.comment %}{{ membership.comment }}{% endif %}</td>
    </tr>
        {% endfor %}
    </table>
    <p>* Personens första uppsättning. </p>
    {% else %}
    <div class="alert alert-warning" role="alert">
        Denna uppsättning har ingen grupp som matchar '{{ group_shortname }}'.
    </div>
    {% endif %}
    </div>
{% endblock %}

batadasen/templates/batadasen/production_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}Uppsättningar{% endblock %}

{% block content %}
<h2>Uppsättningar</h2>
<table class="table table-sm">
    <tr>
        <th>År</th>
        <th>Namn</th>
    </tr>
    {% for production in object_list|dictsortreversed:"number" %}
    <tr>
        <td>{{ production.year }}</td>
        <td>
            <a href="{% url 'batadasen:production_detail' production.number %}">{{ production.short_name }} - {{ production.main_title }}</a>
        </td>
    </tr>
    {% endfor %}
</table>
{% endblock %}