assetmanager/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from assetmanager.views import (
    AssetListView,
    AssetDetailView,
    AssetModelDetailView,
    new_logentry_view,
    new_asset_view,
    new_assetmodel_view,
    new_category_view,
    search_view,
)


app_name = "assetmanager"
urlpatterns = [
    path("assets/", AssetListView.as_view(), name="asset_list"),
    path("assets/add/", new_asset_view, name="asset_add"),
    path("assets/search/", search_view, name="asset_search"),
    path("assets/<int:number>/", AssetDetailView.as_view(), name="asset_detail"),
    path(
        "assets/<int:number>/new-log-entry/", new_logentry_view, name="create_log_entry"
    ),
    path(
        "assetmodels/<int:pk>/",
        AssetModelDetailView.as_view(),
        name="assetmodel_detail",
    ),
    path("assetmodels/add/", new_assetmodel_view, name="assetmodel_add"),
    path("categories/add/", new_category_view, name="category_add"),
    path("", RedirectView.as_view(pattern_name="asset_list", permanent=False)),
]

batadasen/urls.py
from django.urls import path

from . import views

app_name = "batadasen"
urlpatterns = [
    path("activate", views.activation_view, name="activate"),
    path("email_lists/", views.email_list_filter, name="emaillist_list"),
    path(
        "email_lists/<str:alias>/",
        views.EmailListDetailView.as_view(),
        name="emaillist_detail",
    ),
    path("settings/", views.PersonSelfView.as_view(), name="person_settings"),
    path(
        "settings/extra_email/",
        views.ExtraEmailView.as_view(),
        name="person_extra_email",
    ),
    path("persons/", views.PersonListView.as_view(), name="person_list"),
    path("persons/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    path("hundraklubben/", views.Club100.as_view(), name="hundraklubben"),
    path("medals/", views.Medals.as_view(), name="medals"),
    path("productions/", views.ProductionListView.as_view(), name="production_list"),
    path(
        "productions/<int:pk>/",
        views.ProductionDetailView.as_view(),
        name="production_detail",
    ),
    path(
        "productions/<int:pk>/<str:group_shortname>/",
        views.ProductionGroupDetailView.as_view(),
        name="production_group_detail",
    ),
    path(
        "association/",
        views.AssociationYearListView.as_view(),
        name="associationyear_list",
    ),
    path(
        "association/<int:pk>/",
        views.AssociationYearDetailView.as_view(),
        name="associationyear_detail",
    ),
    path(
        "association/<int:pk>/<str:group_shortname>/",
        views.AssociationYearGroupDetailView.as_view(),
        name="associationyear_group_detail",
    ),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
    path("api/users", views.UserList.as_view()),
    path("api/users_count", views.user_count),
    path("no_admin/", views.no_admin_view, name="no_admin"),
    path("", views.index_view, name="index"),
]

internsidor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.http import HttpResponse
from django.views.generic.base import TemplateView

from ajax_select import urls as ajax_select_urls

import batadasen


def auth_check(request):
    """
    Empty response view for use with Nginx auth_request
    """
    if request.user.is_authenticated:
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=401, headers={"WWW-Authenticate": "Bearer"})


if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns = [
        # This is a hack to workaround the fact that the admin logout link uses GET but
        # the mozilla_django_oidc logout page requires a POST request.
        # The logout_get.html simply instructs the user to logout with the regular logout button.
        path(
            "admin/logout/",
            TemplateView.as_view(template_name="batadasen/logout_get.html"),
        ),
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("auth_check", auth_check, name="auth-check"),
        path("", batadasen.views.index_view),
    ]
else:
    urlpatterns = [
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        # A simple login view for dev setups that don't have keycloak available
        path(
            "login/",
            auth_views.LoginView.as_view(template_name="batadasen/dev_login.html"),
            name="login",
        ),
        # Fake the oidc_logout url to make the logout button happy
        path("logout/", auth_views.LogoutView.as_view(), name="oidc_logout"),
        path("", batadasen.views.index_view),
    ]

    # Used to serve uploaded files during development, NOT FOR PRODUCTION USE
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spexflix/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"productions", views.ProductionViewSet)

app_name = "spexflix"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.ProductionList.as_view(), name="index"),
    path(
        "productions/<int:pk>",
        views.ProductionDetail.as_view(),
        name="production-detail",
    ),
    path("video/<int:pk>", views.VideoDetail.as_view(), name="video-detail"),
]

assetmanager/forms.py
from django import forms
from .models import LogEntry, Asset, Owner, get_next_asset_number
from django.utils.translation import gettext_lazy as _
import datetime

from ajax_select.fields import AutoCompleteSelectField, AutoCompleteSelectMultipleField


class CategoryForm(forms.Form):
    name = forms.CharField(label=_("Name"), max_length=100)
    name.widget.attrs["class"] = "form-control"


class AssetModelForm(forms.Form):
    manufacturer = forms.CharField(label=_("Manufacturer"), max_length=100)
    manufacturer.widget.attrs["class"] = "form-control"

    model_name = forms.CharField(label=_("Model name"), max_length=100)
    model_name.widget.attrs["class"] = "form-control"

    model_description = forms.CharField(
        label=_("Model description"), widget=forms.Textarea(attrs={"rows": 2})
    )
    model_description.widget.attrs["class"] = "form-control"

    categories = AutoCompleteSelectMultipleField("categories", label=_("Categories"))
    categories.widget.attrs["class"] = "form-control"


class LogEntryForm(forms.Form):
    timestamp = forms.DateTimeField(label=_("Timestamp"), initial=datetime.datetime.now)
    timestamp.widget.attrs["class"] = "form-control"

    new_status = forms.ChoiceField(
        label=_("New status"), choices=LogEntry.STATUS_CHOICES
    )
    new_status.widget.attrs["class"] = "form-control"

    notes = forms.CharField(label=_("Notes"), widget=forms.Textarea)
    notes.widget.attrs["class"] = "form-control"


class AssetForm(forms.Form):
    number = forms.IntegerField(
        label=_("Number"), min_value=1, initial=get_next_asset_number
    )
    number.widget.attrs["class"] = "form-control"

    model = AutoCompleteSelectField("assetmodels", label=_("Model"))
    model.widget.attrs["class"] = "form-control"

    owner = forms.ModelChoiceField(label=_("Owner"), queryset=Owner.objects.all())
    owner.widget.attrs["class"] = "form-control"

    purchase_time = forms.CharField(
        label=_("Purchase time"), max_length=100, required=False
    )
    purchase_time.widget.attrs["class"] = "form-control"

    purchase_price = forms.CharField(
        label=_("Purchase price"), max_length=100, required=False
    )
    purchase_price.widget.attrs["class"] = "form-control"

    standard_location = forms.CharField(
        label=_("Standard location"), max_length=100, required=False
    )
    standard_location.widget.attrs["class"] = "form-control"

    supplier = forms.CharField(label=_("Supplier"), max_length=100, required=False)
    supplier.widget.attrs["class"] = "form-control"

    description = forms.CharField(
        label=_("Description"), widget=forms.Textarea(attrs={"rows": 2}), required=False
    )
    description.widget.attrs["class"] = "form-control"

    initial_status = forms.ChoiceField(
        label=_("Initial status"),
        choices=LogEntry.STATUS_CHOICES,
        initial=LogEntry.STATUS_UNKNOWN,
    )
    initial_status.widget.attrs["class"] = "form-control"

    initial_log_entry = forms.CharField(
        label=_("Initial log entry"), widget=forms.Textarea(attrs={"rows": 2})
    )
    initial_log_entry.widget.attrs["class"] = "form-control"

    def clean_number(self):
        data = self.cleaned_data.get("number")
        if data is None:
            raise forms.ValidationError(_("number cannot be empty"))
        if Asset.objects.filter(number=data).exists():
            raise forms.ValidationError(
                _("Another asset already has this number: ") + str(data)
            )

        return data

assetmanager/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from django.views import generic
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.exceptions import PermissionDenied

from .models import Asset, AssetModel, LogEntry, Category
from .forms import LogEntryForm, AssetForm, AssetModelForm, CategoryForm

from ajax_select import register, LookupChannel


class AssetListView(LoginRequiredMixin, generic.ListView):
    model = Asset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["categories"] = Category.objects.all()
        return context

    def get_queryset(self):
        if "category" in self.request.GET:
            return Asset.objects.filter(
                model__categories__name=self.request.GET.get("category")
            )
        else:
            return Asset.objects.all()


class AssetDetailView(LoginRequiredMixin, generic.DetailView):
    model = Asset
    slug_field = "number"
    slug_url_kwarg = "number"


class AssetModelDetailView(LoginRequiredMixin, generic.DetailView):
    model = AssetModel


@login_required
def new_logentry_view(request, number):
    asset_inst = get_object_or_404(Asset, number=number)

    if request.method == "POST":
        form = LogEntryForm(request.POST)

        if form.is_valid():
            logentry_inst = LogEntry(**form.cleaned_data)
            logentry_inst.asset = asset_inst
            logentry_inst.user = request.user
            logentry_inst.save()

            return HttpResponseRedirect(
                reverse(
                    "assetmanager:asset_detail", kwargs={"number": asset_inst.number}
                )
            )

    else:
        form = LogEntryForm()

        if asset_inst.log_entries.exists():
            latest_status = asset_inst.log_entries.latest("timestamp")
            form.fields["new_status"].initial = latest_status
        else:
            form.fields["new_status"].initial = LogEntry.STATUS_UNKNOWN

    return render(
        request,
        "assetmanager/logentry_form.html",
        {"form": form, "asset_inst": asset_inst},
    )


# @permission_required('assetmanager.add_asset')
@never_cache
@login_required
def new_asset_view(request):
    if request.method == "POST":
        form = AssetForm(request.POST)

        if form.is_valid():
            initial_status = form.cleaned_data.pop("initial_status")
            initial_log_entry = form.cleaned_data.pop("initial_log_entry")

            asset_inst = Asset(**form.cleaned_data)
            asset_inst.save()

            entry = LogEntry(
                asset=asset_inst, notes=initial_log_entry, new_status=initial_status
            )
            entry.save()

            return HttpResponseRedirect(
                reverse(
                    "assetmanager:asset_detail", kwargs={"number": asset_inst.number}
                )
            )
    else:
        form = AssetForm()

    return render(request, "assetmanager/asset_form.html", {"form": form})


# @permission_required('assetmanager.add_assetmodel')
@login_required
def new_assetmodel_view(request):
    if request.method == "POST":
        form = AssetModelForm(request.POST)

        if form.is_valid():
            assetmodel_inst = AssetModel()
            assetmodel_inst.manufacturer = form.cleaned_data.pop("manufacturer")
            assetmodel_inst.model_name = form.cleaned_data.pop("model_name")
            assetmodel_inst.model_description = form.cleaned_data.pop(
                "model_description"
            )
            assetmodel_inst.save()
            for cat in form.cleaned_data.pop("categories"):
                assetmodel_inst.categories.add(cat)

            assetmodel_inst.save()

            return HttpResponseRedirect(reverse("assetmanager:asset_add"))
    else:
        form = AssetModelForm()

    return render(request, "assetmanager/assetmodel_form.html", {"form": form})


# @permission_required('assetmanager.add_category')
@login_required
def new_category_view(request):
    if request.method == "POST":
        form = CategoryForm(request.POST)

        if form.is_valid():
            category_inst = Category(**form.cleaned_data)
            category_inst.save()

            return HttpResponseRedirect(reverse("assetmanager:assetmodel_add"))
    else:
        form = CategoryForm()

    return render(request, "assetmanager/category_form.html", {"form": form})


@login_required
def search_view(request):
    if request.method == "GET":
        asset_id = request.GET.get("id")
        if Asset.objects.filter(number=asset_id).exists():
            return HttpResponseRedirect(
                reverse("assetmanager:asset_detail", args=[asset_id])
            )

        return HttpResponseRedirect(reverse("assetmanager:asset_list"))


@register("assetmodels")
class AssetModelLookup(LookupChannel):
    model = AssetModel

    def check_auth(self, request):
        if not request.user.is_authenticated:
            raise PermissionDenied

    def get_query(self, q, request):
        return AssetModel.objects.filter(
            Q(model_name__icontains=q) | Q(manufacturer__icontains=q)
        )

    def format_item_display(self, item):
        return '<span class="assetmodel">%s %s</span>' % (
            item.manufacturer,
            item.model_name,
        )


@register("categories")
class CategoryLookup(LookupChannel):
    model = Category

    def check_auth(self, request):
        if not request.user.is_authenticated:
            raise PermissionDenied

    def get_query(self, q, request):
        return Category.objects.filter(Q(name__icontains=q))

    def format_item_display(self, item):
        return '<span class="category">%s</span>' % item.name

assetmanager/templates/assetmanager/asset_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Asset" %} {{ object.number }}{% endblock %}

{% block content %}
    <h2>{% trans "Asset details" %}</h2>
    <table class="table table-sm">
        <tbody>
            <tr>
                <td class="table-fit">Number:</td>
                <td>{{ object.number }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Model" %}</td>
                <td><a href="{% url 'assetmanager:assetmodel_detail' object.model_id %}">{{ object.model }}</a></td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Status" %}</td>
                <td>{{ object.status_readable }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Standard location" %}</td>
                <td>{{ object.standard_location }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Owner" %}</td>
                <td>{{ object.owner }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Purchase time" %}</td>
                <td>{{ object.purchase_time }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Purchase price" %}</td>
                <td>{{ object.purchase_price }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Supplier" %}</td>
                <td>{{ object.supplier }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Comments" %}</td>
                <td>{{ object.comments }}</td>
            </tr>
        </tbody>
    </table>
    <h3>{% trans "Log" %}</h3>
    <table class="table table-sm">
        <tr>
            <th>{% trans "Timestamp" %}</th>
            <th>{% trans "Status" %}</th>
            <th>{% trans "Notes" %}</th>
            <th>{% trans "Entered by" %}</th>
        </tr>
        {% for event in object.log_entries.all %}
            <tr>
                <td>
                {{ event.timestamp|date:"Y-m-d H:i:s"}} 
                </td>
                <td>
                {{ event.get_new_status_display }}
                </td>
                <td>
                {{ event.notes }}
                </td>
                <td>
                {% if event.user.person %} 
                    {% if event.user.person.privacy_setting != 'PVT' %}
                    <a href="{% url 'batadasen:person_detail' event.user.person.member_number %}">{{ event.user.person.full_name }}</a>
                    {% endif %}
                {% elif event.user %}
                    {{ event.user }}
                {% endif %}
                </td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'assetmanager:create_log_entry' object.number %}" class="btn btn-primary">{% trans "Add log entry" %}</a>
{% endblock %}

assetmanager/templates/assetmanager/asset_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {{ form.media }}
    <form method="post">{% csrf_token %}
        <table class="table">
            {% for field in form %}
                <tr>
                    <th>
                        {% if field.field.required %}
                        <label class="required-field" for="{{ field.name }}">{{field.label}} *</label>
                        {% else %}
                        <label for="{{ field.name }}">{{ field.label }}</label>
                        {% endif %}
                    </th>
                    <td>
                        {{ field.errors}}
                        {{ field }}
                        {% if field is form.model %}
                            <a href="{% url 'assetmanager:assetmodel_add' %}" class="btn btn-secondary">{% trans 'Add model' %}</a>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input class="btn btn-primary" type="submit" value="{% trans 'Add' %}" />
    </form>
{% endblock %}

assetmanager/templates/assetmanager/asset_list.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Assets{% endblock %}
 {% block content %}
<div class="row" id="toprow">
    <div class="col-sm">
        <h2>{% trans "Assets" %}</h2>
    </div>
    <div id="add-asset-button">
        <a class="btn btn-primary" href="{% url 'assetmanager:asset_add' %}">{% trans "Add asset" %}</a>
    </div>
</div>
<div>
	<h5 class="d-sm-inline-block">{% trans "Only show category:" %}</h5>
	{% for category in categories %}
	<a href="{% url 'assetmanager:asset_list' %}?category={{ category|urlencode }}">
		<span>{{ category }}</span></a>
	{% endfor %}
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                {% trans "ID" %}
            </th>
            <th>
                {% trans "Model" %}
            </th>
            <th>
                {% trans "Status" %}
            </th>
        </tr>
    </thead>
    <tbody>
        {% for asset in object_list %}
        <tr class="table-row">
            <td class="table-cell"><a class="table-link" href="{% url 'assetmanager:asset_detail' asset.number %}">{{ asset.number }}</a></td>
            <td class="table-cell"><a class="table-link" href="{% url 'assetmanager:asset_detail' asset.number %}">{{ asset.model}}</a></td>
            <td class="table-cell"><a class="table-link" href="{% url 'assetmanager:asset_detail' asset.number %}">{{ asset.status_readable}}</a></td>
        </tr>

        {% endfor %}
    </tbody>
</table>

{% endblock %}

assetmanager/templates/assetmanager/assetmodel_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h2>{% trans "Asset model" %}</h2>
    <table class="table">
        <tbody>
            <tr>
                <td class="table-fit">{% trans "Manufacturer" %}:</td>
                <td>{{ object.manufacturer }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Model name" %}:</td>
                <td>{{ object.model_name }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Description" %}:</td>
                <td>{{ object.model_description }}</td>
            </tr>
            <tr>
                <td class="table-fit">{% trans "Categories" %}:</td>
                <td>
                    <ul>
                        {% for cat in object.categories.all %}
                        <li>{{ cat }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
{% endblock %}

assetmanager/templates/assetmanager/assetmodel_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    {{ form.media }}
    <form method="post">{% csrf_token %}
        {{ form.non_field_errors }}
        <table class="table">
            <tr>
                <th>
                    <label for="{{ form.manufacturer.id_for_label }}">{% trans "Manufacturer" %}:</label>
                </th>
                <td>
                    {{form.manufacturer.errors}} 
                    {{ form.manufacturer}}
                </td>
            </tr>
            <tr>
                <th>
                    <label for="{{ form.model_name.id_for_label }}">{% trans "Model name" %}:</label>
                </th>
                <td>
                    {{form.model_name.errors}} 
                    {{ form.model_name}}
                </td>
            </tr>
            <tr>
                <th>
                    <label for="{{ form.model_description.id_for_label }}">{% trans "Description" %}:</label>
                </th>
                <td>
                    {{form.model_description.errors}} 
                    {{ form.model_description}}
                </td>
            </tr>
            <tr>
                <th>
                    <label for="{{ form.categories.id_for_label }}">{% trans "Categories" %}:</label>
                </th>
                <td>
                    {{form.categories.errors}} 
                    {{ form.categories}}
                    <a class="btn btn-secondary" href="{% url 'assetmanager:category_add' %}">{% trans "Add new category" %}</a>
                </td>
            </tr>
        </table>
        <input class="btn btn-primary" type="submit" value='{% trans "Add model" %}'/>
    </form>
{% endblock %}

assetmanager/templates/assetmanager/category_form.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <form method="post">{% csrf_token %}
        <table class="table">
            {{ form }}
        </table>
        <input class="btn btn-primary" type="submit" value="{% trans "Add" %}" />
    </form>
    {{ form.media }}
{% endblock %}

assetmanager/templates/assetmanager/logentry_form.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans "New log entry" %}{% endblock %}

{% block content %}
<h2>{% trans "New log entry for asset number " %}{{ asset_inst.number }}</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input class="btn btn-primary" type="submit" value="Save" />
    <a href="{% url 'assetmanager:asset_detail' asset_inst.number %}" class="btn btn-light">Cancel</a>
</form>

{% endblock %}