assetmanager/urls.py
from django.urls import path
from django.views.generic.base import RedirectView
from assetmanager.views import (
    AssetListView,
    AssetDetailView,
    AssetModelDetailView,
    new_logentry_view,
    new_asset_view,
    new_assetmodel_view,
    new_category_view,
    search_view,
)


app_name = "assetmanager"
urlpatterns = [
    path("assets/", AssetListView.as_view(), name="asset_list"),
    path("assets/add/", new_asset_view, name="asset_add"),
    path("assets/search/", search_view, name="asset_search"),
    path("assets/<int:number>/", AssetDetailView.as_view(), name="asset_detail"),
    path(
        "assets/<int:number>/new-log-entry/", new_logentry_view, name="create_log_entry"
    ),
    path(
        "assetmodels/<int:pk>/",
        AssetModelDetailView.as_view(),
        name="assetmodel_detail",
    ),
    path("assetmodels/add/", new_assetmodel_view, name="assetmodel_add"),
    path("categories/add/", new_category_view, name="category_add"),
    path("", RedirectView.as_view(pattern_name="asset_list", permanent=False)),
]

batadasen/urls.py
from django.urls import path

from . import views

app_name = "batadasen"
urlpatterns = [
    path("activate", views.activation_view, name="activate"),
    path("email_lists/", views.email_list_filter, name="emaillist_list"),
    path(
        "email_lists/<str:alias>/",
        views.EmailListDetailView.as_view(),
        name="emaillist_detail",
    ),
    path("settings/", views.PersonSelfView.as_view(), name="person_settings"),
    path(
        "settings/extra_email/",
        views.ExtraEmailView.as_view(),
        name="person_extra_email",
    ),
    path("persons/", views.PersonListView.as_view(), name="person_list"),
    path("persons/<int:pk>/", views.PersonDetailView.as_view(), name="person_detail"),
    path("hundraklubben/", views.Club100.as_view(), name="hundraklubben"),
    path("medals/", views.Medals.as_view(), name="medals"),
    path("productions/", views.ProductionListView.as_view(), name="production_list"),
    path(
        "productions/<int:pk>/",
        views.ProductionDetailView.as_view(),
        name="production_detail",
    ),
    path(
        "productions/<int:pk>/<str:group_shortname>/",
        views.ProductionGroupDetailView.as_view(),
        name="production_group_detail",
    ),
    path(
        "association/",
        views.AssociationYearListView.as_view(),
        name="associationyear_list",
    ),
    path(
        "association/<int:pk>/",
        views.AssociationYearDetailView.as_view(),
        name="associationyear_detail",
    ),
    path(
        "association/<int:pk>/<str:group_shortname>/",
        views.AssociationYearGroupDetailView.as_view(),
        name="associationyear_group_detail",
    ),
    path("statistics/", views.StatisticsView.as_view(), name="statistics"),
    path("api/users", views.UserList.as_view()),
    path("api/users_count", views.user_count),
    path("no_admin/", views.no_admin_view, name="no_admin"),
    path("", views.index_view, name="index"),
]

internsidor/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from django.http import HttpResponse
from django.views.generic.base import TemplateView

from ajax_select import urls as ajax_select_urls

import batadasen


def auth_check(request):
    """
    Empty response view for use with Nginx auth_request
    """
    if request.user.is_authenticated:
        return HttpResponse(status=204)
    else:
        return HttpResponse(status=401, headers={"WWW-Authenticate": "Bearer"})


if "mozilla_django_oidc" in settings.INSTALLED_APPS:
    urlpatterns = [
        # This is a hack to workaround the fact that the admin logout link uses GET but
        # the mozilla_django_oidc logout page requires a POST request.
        # The logout_get.html simply instructs the user to logout with the regular logout button.
        path(
            "admin/logout/",
            TemplateView.as_view(template_name="batadasen/logout_get.html"),
        ),
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        path("oidc/", include("mozilla_django_oidc.urls")),
        path("auth_check", auth_check, name="auth-check"),
        path("", batadasen.views.index_view),
    ]
else:
    urlpatterns = [
        path("admin/", admin.site.urls),
        path("batadasen/", include("batadasen.urls")),
        path("lissinv/", include("assetmanager.urls")),
        path("showcounter/", include("showcounter.urls")),
        path("spexflix/", include("spexflix.urls")),
        path("ajax_select/", include(ajax_select_urls)),
        # A simple login view for dev setups that don't have keycloak available
        path(
            "login/",
            auth_views.LoginView.as_view(template_name="batadasen/dev_login.html"),
            name="login",
        ),
        # Fake the oidc_logout url to make the logout button happy
        path("logout/", auth_views.LogoutView.as_view(), name="oidc_logout"),
        path("", batadasen.views.index_view),
    ]

    # Used to serve uploaded files during development, NOT FOR PRODUCTION USE
    if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

showcounter/urls.py
from django.urls import path

from showcounter import views

app_name = "showcounter"
urlpatterns = [
    path("production/<int:number>", views.production, name="production"),
    path("", views.overview, name="overview"),
]

spexflix/urls.py
from django.urls import path, include
from rest_framework import routers
from . import views

router = routers.DefaultRouter()
router.register(r"productions", views.ProductionViewSet)

app_name = "spexflix"
urlpatterns = [
    path("api/", include(router.urls)),
    path("", views.ProductionList.as_view(), name="index"),
    path(
        "productions/<int:pk>",
        views.ProductionDetail.as_view(),
        name="production-detail",
    ),
    path("video/<int:pk>", views.VideoDetail.as_view(), name="video-detail"),
]

batadasen/views.py
from datetime import datetime
from django.conf import settings
from django.contrib import admin
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import connection
from django.db.models import Q, Count, Min, F
from django.db.models.functions import Collate
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.views.generic import (
    DetailView,
    ListView,
    UpdateView,
    CreateView,
    TemplateView,
)
from django_filters.filterset import FilterSet
import django_tables2 as tables

from rest_framework import generics, filters
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from rest_framework_api_key.permissions import HasAPIKey
import django_filters

from . import forms, models, serializers
from showcounter.models import Performance

if settings.PROVISION_GSUITE_ACCOUNTS:
    from . import gsuite

User = get_user_model()


def swedish_order(field: str):
    """Use collation to get Swedish ordering for a field.

    This collation is not available in SQLite so it is skipped during local development."""
    if connection.vendor == "postgresql":
        return Collate(F(field), "sv-SE-x-icu")
    return field


def activation_view(request):
    token = request.GET.get("token")
    activations = models.UserActivation.objects.filter(token=token)

    bad_token = False
    if token is None or not activations.exists():
        bad_token = True
    else:
        if timezone.now() > activations.first().valid_until:
            bad_token = True

    if bad_token:
        return HttpResponse(
            "Du har nog följt en gammal länk eller så har den kopierats fel"
        )

    activation = activations.first()
    person = activation.person

    if request.method == "POST":
        form = forms.ActivationForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]

            user = User(username=username)
            user.save()

            if person.user is not None:
                person.user.delete()

            person.user = user
            person.save()

            if (
                settings.PROVISION_GSUITE_ACCOUNTS
                and activation.provision_gsuite_account
            ):
                gsuite.create_user(
                    person.user.username, person.first_name, person.last_name
                )

            activations.delete()

            return redirect("batadasen:person_settings")

    else:
        form = forms.ActivationForm()

    return render(request, "batadasen/activate.html", {"form": form, "person": person})


@method_decorator(login_required, name="dispatch")
class EmailListListView(ListView):
    model = models.EmailList

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["email_domain"] = settings.EMAIL_DOMAIN
        return context


@method_decorator(login_required, name="dispatch")
class EmailListDetailView(DetailView):
    model = models.EmailList
    fields = ["recipients"]
    slug_field = "alias"
    slug_url_kwarg = "alias"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["email_domain"] = settings.EMAIL_DOMAIN
        if context["object"].alias.endswith("gruppledare"):
            context["gruppledare"] = True
        return context


class PersonTable(tables.Table):
    member_number = tables.URLColumn(verbose_name="Medlem")
    spex_name = tables.Column(default="")

    class Meta:
        model = models.Person
        template_name = "django_tables2/bootstrap4-responsive.html"
        fields = ("member_number", "first_name", "last_name", "spex_name")
        row_attrs = {
            "class": lambda record: "text-muted font-italic" if record.deceased else ""
        }


@method_decorator(login_required, name="dispatch")
class PersonListView(tables.SingleTableView):
    table_class = PersonTable
    queryset = models.Person.objects.filter(member_number__lt=5000).all()
    template_name = "person_list.html"
    table_pagination = False


@method_decorator(login_required, name="dispatch")
class PersonDetailView(DetailView):
    model = models.Person


@method_decorator(login_required, name="dispatch")
class PersonSelfView(UpdateView):
    form_class = forms.PersonForm
    template_name = "batadasen/person_settings.html"
    success_url = reverse_lazy("batadasen:person_settings")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if "object" in context:
            context["extra_emails"] = models.ExtraEmail.objects.filter(
                person=context["object"]
            )
        return context

    def get_object(self, queryset=None):
        return models.Person.objects.filter(user=self.request.user).first()


@method_decorator(login_required, name="dispatch")
class ExtraEmailView(CreateView):
    form_class = forms.ExtraEmailForm
    template_name = "batadasen/extraemail_form.html"
    success_url = reverse_lazy("batadasen:person_settings")

    def form_valid(self, form):
        if form.is_valid():
            extra_email = form.save(commit=False)
            extra_email.person = self.request.user.person
            extra_email.save()
        return redirect("batadasen:person_settings")


@method_decorator(login_required, name="dispatch")
class ProductionListView(ListView):
    model = models.Production


@method_decorator(login_required, name="dispatch")
class ProductionDetailView(DetailView):
    model = models.Production

    # This dance is done to order the memberships in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = []
        for group in context["object"].groups.all():
            memberships = group.memberships.annotate(
                first_production_id=Min(
                    "person__production_memberships__group__production__pk"
                )
            ).order_by(
                F("title").asc(nulls_last=True),
                swedish_order("person__first_name"),
                swedish_order("person__last_name"),
            )

            if not memberships.exists():
                continue
            result_group = dict()
            result_group["group"] = group
            result_group["memberships"] = memberships
            groups.append(result_group)
        context["groups"] = groups

        previous_production = (
            self.model.objects.filter(number__lt=context["object"].number)
            .order_by("-number")
            .only("number")
            .first()
        )
        context["previous"] = (
            previous_production.number if previous_production else None
        )

        next_production = (
            self.model.objects.filter(number__gt=context["object"].number)
            .only()
            .order_by("number")
            .only("number")
            .first()
        )
        context["next"] = next_production.number if next_production else None

        return context


@method_decorator(login_required, name="dispatch")
class ProductionGroupDetailView(DetailView):
    model = models.Production
    template_name = "batadasen/production_group_detail.html"  # skapa ev ny template

    # This dance is done to order the memberships in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        previous_production = (
            self.model.objects.filter(number__lt=context["object"].number)
            .order_by("-number")
            .only("number")
            .first()
        )
        context["previous"] = (
            previous_production.number if previous_production else None
        )

        next_production = (
            self.model.objects.filter(number__gt=context["object"].number)
            .only()
            .order_by("number")
            .only("number")
            .first()
        )
        context["next"] = next_production.number if next_production else None

        group_shortname = self.kwargs["group_shortname"]
        context["group_shortname"] = group_shortname

        group = context["object"].groups.filter(group_type_id=group_shortname).first()
        if not group:
            return context

        memberships = group.memberships.annotate(
            first_production_id=Min(
                "person__production_memberships__group__production__pk"
            )
        ).order_by(
            F("title").asc(nulls_last=True),
            swedish_order("person__first_name"),
            swedish_order("person__last_name"),
        )

        context["group"] = group
        context["memberships"] = memberships

        return context


@method_decorator(login_required, name="dispatch")
class AssociationYearListView(ListView):
    model = models.AssociationYear


@method_decorator(login_required, name="dispatch")
class AssociationYearDetailView(DetailView):
    model = models.AssociationYear

    # This dance is done to order the activities in each group by title
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        groups = []
        for group in context["object"].groups.all():
            activities = group.activities.order_by(
                F("title").asc(nulls_last=True),
                swedish_order("person__first_name"),
                swedish_order("person__last_name"),
            )

            if not activities.exists():
                continue
            result_group = {
                "group": group,
                "activities": activities,

batadasen/templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> {% load static %}
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="icon" href="/static/images/lisse-combined-256-to-16.ico" sizes="16x16 32x32 48x48 64x64 128x128"
        type="image/vnd.microsoft.icon">

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script> -->


    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    {% load i18n %}
    <div id="wrapper">
        <div id="sidebar-wrapper" class="position-fixed">
            <nav class="sidebar-nav nav flex-column">
                <a class="sidebar-brand" href="/"><img src="{% static 'images/lisse.png' %}"></a>
                <h5>Spextjänster</h5>
                <a class="nav-link" href="https://wiki.studentspex.se">Wiki</a>
                <a class="nav-link" href="{% url 'spexflix:index' %}">Spexflix</a>
                <h5>Internsidor</h5>
                <a class="nav-link" href="{% url 'batadasen:person_settings' %}">Inställningar</a>
                <a class="nav-link" href="{% url 'batadasen:production_list' %}">Uppsättningar</a>
                <a class="nav-link" href="{% url 'batadasen:associationyear_list' %}">Verksamhetsår</a>
                <a class="nav-link" href="{% url 'batadasen:person_list' %}">Medlemmar</a>
                <a class="nav-link" href="{% url 'batadasen:emaillist_list' %}">Epostlistor</a>
                <a class="nav-link" href="{% url 'assetmanager:asset_list' %}">Inventarier</a>
                <a class="nav-link" href="{% url 'showcounter:overview' %}">Föreställningsräknare</a>
                <h5>Gamla internsidor</h5>
                <a class="nav-link" href="https://old.studentspex.se/nominera/index.php">Nominera</a>
                <a class="nav-link" href="https://old.studentspex.se/ansokan/index.php">Internansökan</a>
                <a class="nav-link" href="https://old.studentspex.se/spexpay/index.php">Spexpay</a>
                <span class="spacer"></span>
                {% if request.user.is_authenticated %}
                <form id="logout-form" action="{% url 'oidc_logout' %}" method="post">
                    {% csrf_token %}
                </form>
                <a class="nav-link logout" href="#" onclick="document.forms['logout-form'].submit();">Logga ut</a>
                {% endif %}
                {% if request.user.is_staff %}
                <a class="nav-link" id="admin-link" href="{% url 'admin:index' %}">Admin</a>
                {% endif %}
            </nav>
        </div>
        <div id="page-content-wrapper">
            <div id="page-header" class="row">
                <button class="btn" onclick="toggleSidebar()">&#8801;</button>
            </div>
            <main class="container-fluid">
                {% block content %} {% endblock %}
            </main>
        </div>
    </div>

    <script>
        function toggleSidebar() {
            document.getElementById("wrapper").classList.toggle("toggled");
        }
    </script>
</body>

</html>